config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  get "/dashboard", to: "pages#dashboard", as: :dashboard

  resources :profiles, only: [:show, :new, :create, :edit, :update]

  resources :matches, only: [:show, :new] do
    resources :messages, only: [:index]
  end
  resources :messages, only:[:create]
  resources :questions, only: [:index, :show]
  resources :user_answers, only: [:create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  def answered_by(user)
    user.answers.collect(&:question).include?(self)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.select {|a| a.answered_by(current_user) ? false : a }

  end

  def show
    @question = Question.find(params[:id])
  end

  def update



  end
end

app/views/questions/show.html.erb
<div class="Qpage">

  <div class="form-box-full-width">
  <h3 class="title-border">Personality Calculator</h3>

    <div class="question-box">
   <h4> <%= @question.question %> </h4>
    </div>

     <div class="answer-box">
        <% @question.answers.each do |ans| %>
         <%= link_to user_answers_path(picked_answer_id: ans.id), method: :post do %>
            <div class="btn btn-questions">
              <%= ans.answer %>
            </div>
          <% end %>
      <% end %>
     </div>

  </div>



<!--  -->
 </div>
</div>


 </div>
</div>