config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  get "/dashboard", to: "pages#dashboard", as: :dashboard

  resources :profiles, only: [:show, :new, :create, :edit, :update]

  resources :matches, only: [:show, :new] do
    resources :messages, only: [:index]
  end
  resources :messages, only:[:create]
  resources :questions, only: [:index, :show]
  resources :user_answers, only: [:create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard/_profile_tab_pane.html.erb
<div class="profile-body">
  <div class="profile-box">
    <div class="profile-row">
      <div class="profile-icon"><%= image_tag "sporty.png", height: 30 %></div>
      <div class="profile-trait">Sporty</div>
      <div class="stats-bar">
        <div class="stats-bar-view" style="width:<%= current_user.profile.sporty %>0%">
        </div>
      </div>
    </div>
    <div class="profile-row">
      <div class="profile-icon"><%= image_tag "party.png", height: 30 %> </div>
      <div class="profile-trait">Party</div>
      <div class="stats-bar">
        <div class="stats-bar-view" style="width:<%= current_user.profile.party %>0%">
        </div>
      </div>
    </div>
    <div class="profile-row">
      <div class="profile-icon"><%= image_tag "nerdy.png", height: 30 %> </div>
      <div class="profile-bar">
        <div class="profile-trait">Nerdy</div>
          <div class="stats-bar">
            <div class="stats-bar-view" style="width:<%= current_user.profile.nerdy %>0%">
            </div>
          </div>
      </div>
    </div>
    <div class="profile-row">
      <div class="profile-icon"><%= image_tag "organized.png", height: 25 %> </div>
      <div class="profile-trait">Organized</div>
      <div class="stats-bar">
        <div class="stats-bar-view" style="width:<%= current_user.profile.organized %>0%">
        </div>
      </div>
    </div>
    <div class="profile-row">
      <div class="profile-icon"><%= image_tag "spiritual.png", height: 30 %> </div>
      <div class="profile-trait">Spiritual</div>
      <div class="stats-bar">
        <div class="stats-bar-view" style="width:<%= current_user.profile.spiritual %>0%">
        </div>
      </div>
    </div>
  </div>
  <div class="button-edit">
    <%= link_to "Edit your profile", edit_profile_path(current_user.profile) %>
  </div>
</div>