config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  get "/dashboard", to: "pages#dashboard", as: :dashboard

  resources :profiles, only: [:show, :new, :create, :edit, :update]

  resources :matches, only: [:show, :new] do
    resources :messages, only: [:index]
  end
  resources :messages, only:[:create]
  resources :questions, only: [:index, :show]
  resources :user_answers, only: [:create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :user_matches
  has_many :users, through: :user_matches
  has_many :messages

  def last_message
    self.messages.last&.message
  end

  def calc_blur
    message_count = self.messages.length
    message_count = 5 if message_count > 5
    "#{5 - message_count}px"
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def new
    # 1. try to find a match
    # 1.a go through all other users
    # 1.b apply the filtering rules :
    #.     - same city ?
    #.     - gender matches current user's pref' ?
    other_users = User.where.not(id: current_user.id).select {|u| (u.profile.city == current_user.profile.city) &&  (u.profile.gender == current_user.profile.preference)}

    new_matches_only = other_users.select {|a| current_user.matches.map{|m| m.users}.flatten.include?(a) ? false : a }
    @match = Match.new
    @match.users << current_user << new_matches_only.first
    @match.save!
      # 1.c check if the match already exists
      #.    - go through all current_user's matches
      # already_exists = false
      # current_user.matches.each do |current_match|
      #   if current_match.users.where(id: ou.id).first
      #     already_exists = true
      #     matches << current_match
      #   end
      # end

      # if !already_exists
      #   # create the match
      #   new_match = Match.new(users: [current_user, ou])
      #   new_match.save!
      #   matches << new_match
      # end

      # @match = matches.last || true
  end



    # if there is one create the match in the database
    # and display a link to it in the view
    # if not, display "sorry come back later"

  def show
    @match_id = params[:id]  # 13
    the_match = Match.find(@match_id)
    # get the current user id
    @user_id = current_user.id
    # find the other person's user_match :
    filtered_user_matches = the_match.user_matches.select do |user_match|
      user_match.user_id != current_user.id
    end
    @other_user_match = filtered_user_matches.first
    @other_user = @other_user_match.user
    # get the list of messages to display
    @messages = the_match.messages
  end

  def delete
  end

end

app/views/matches/new.html.erb
<div class="Calcpage">
    <div class="Calcbox">


        <div class="calctophalf" id="calculatingBar">
          <div class="loading-page">
            <div class="counter">
              <h2>Calculating</h2>
              <h1>0%</h1>
            <hr/>
            </div>
          </div>
        </div>

      <div class="calcbttmhalf" id="div11">

          <div class="lefthalf">

         <span class="imagee-sizee"> <%= image_tag "Showman.png", class: "imagee-sizee" %> </span>
          <div class="curtain -left">
          </div>
          </div>


           <div class="righthalf">

              <h5 class="righthalf-Ymatch">You have a match!</h5>
              <%= link_to profile_path(@match.users.where.not(id: current_user.id).first.profile) do %>
                <div class="avatar avatar-sm avatar-reveal" style="background-image: url(<%= @match.users.where.not(id: current_user.id).first.profile.photo.url ? @match.users.where.not(id: current_user.id).first.profile.photo.url  : 'http://dl1.cbsistatic.com/i/2017/10/19/925f2651-018c-4d76-baf2-3ce4de2ecdb4/a9d0a0ebc85b66e01318f74b0be11da8/imgingest-7427792717055670780.png';  %> );" >
                </div>
              <% end %>

              <div class="curtain -right">

              </div>
         </div>




          <h5 class="open">View your Match</h5>


      </div>

     </div>
</div>


<!--
    <% if @match %>
        <h1>Match Found!</h1>
        <div>
          <%= link_to "Your match", match_path(@match) %>
        </div>
      <% else %>
        <div>
         <%= link_to "Dashboard", dashboard_path %>
        </div>
      <% end %>

-->

app/views/matches/show.html.erb
<div class="chat-page">
      <div class="chat-header">
      <%= link_to @other_user.profile, class: "on-top" do  %>
        <div class="avatar-sharp-wrapper avatar-sharp-wrapper-xs avatar-wrapper-under-chat-above">
          <div class="avatar avatar-xs avatar-wrapper-block" style="background-image: url(<%= @other_user.profile.photo.url ? @other_user.profile.photo.url : 'http://dl1.cbsistatic.com/i/2017/10/19/925f2651-018c-4d76-baf2-3ce4de2ecdb4/a9d0a0ebc85b66e01318f74b0be11da8/imgingest-7427792717055670780.png';  %> );" >
          </div>
        </div>
      <% end %>

      <h3 class="reciever-namee"><%= @other_user.profile.username %>, <%= @other_user.profile.age %></h3>
      </div>

    <div class="chat-bubbles">

        <% @messages.each do |message| %>
            <div class="<%= message.user == current_user ? "bubble-right" : "bubble-left" %>">
              <div class="chat-bubble">
                <p>
                   <%= message.message %>
                </p>
                <div class="needs_to_be_rendered" datetime="<%= message.created_at %>"></div>
              </div>

            </div>
          <% end %>
     </div>


     <div class="chat-inputs">
      <!-- Form -->
        <div class="chatform">
          <input type="text" class="chat-input">
          <input type="hidden" id="match_id" value="<%= @match_id %>" />
          <input type="hidden" id="user_id" value="<%= @user_id %>" />
          <button disabled class="brand-button-medium btn chat-send fa fa-paper-plane">  </button>
        </div>
     </div>
</div>